parameters:
  name: 'Conda build job'
  vmImage: 'Ubuntu-18.04'
  py_maj: '3'
  py_min: '6'
  conda_bld: '3.16.3'

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 360
  
  pool:
    vmImage: ${{ parameters.vmImage }}
    
  steps: 
  
  - ${{ if or(contains(parameters.vmImage, 'macOS'),contains(parameters.vmImage, 'Ubuntu')) }}:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: 'Add conda to PATH'

  - ${{ if contains(parameters.vmImage, 'win') }}:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: 'Add conda to PATH'

  - ${{ if contains(parameters.vmImage, 'macOS') }}:
    - bash: |
        sudo chown -R $USER $CONDA
      displayName: 'MacOS ownership workaround'
 
  - bash: |
        conda config --set always_yes yes --set changeps1 no && \
        conda update -q conda && \
        conda info -a && \
        conda config --add channels https://conda.anaconda.org/conda-forge
    displayName: 'Conda config and info'

  - bash: |
        conda env create -n psenv -f environment.yml python=${{ parameters.py_maj }}.${{ parameters.py_min }}
    displayName: Install ProcessScheduler to a dedicated environment

  - bash: |
      source activate psenv && \
      conda install pip && \
      pip install coverage plotly kaleido
    displayName: 'Install additional packages (plotly, kaleido, coverage)'

  - bash: |
      source activate psenv && \
      python -c 'from processscheduler import *'
    displayName: 'Test import'

  - bash: |
      source activate psenv && \
      python -m unittest
    displayName: 'Run unittest suite'

  - bash: |
      source activate psenv && \
      cd benchmark &&\
      python benchmark_dev_team.py --plot=False &&\
      cd ..
    displayName: 'Run benchmark'

  - ${{ if eq(parameters.name, 'Ubuntu_20_04_python39') }}:
    - bash: |
        source activate psenv && \
        coverage run -m unittest && \
        coverage report -m && \
        coverage html && \
        bash <(curl -s https://codecov.io/bash)
      displayName: 'Coverage and export to codecov (Linux py39 only)'

  - ${{ if not(startsWith(parameters.name, 'Windows')) }}:
    - bash: |
        source activate psenv && \
        cd doc && \
        conda install -c conda-forge pandoc && \
        pip install -r requirements.txt && \
        make html
      displayName: 'Build Sphinx documentation (Mac and Linux only)'
