from setuptools import setup, find_packages

setup(name='ProcessScheduler',
      version='0.1-dev',
      description='A python package to formulate and solve resource-constrained scheduling problems',
      url='https://github.com/tpaviot/ProcessScheduler',
      author='Thomas Paviot',
      author_email='tpaviot@gmail.com',
      license='GPLv3',
      py_modules = ['processscheduler'],
      install_requires=['z3-solver'],
      classifiers=[
            #'Development Status :: 1 - Planning',
            #'Development Status :: 2 - Pre-Alpha',
            'Development Status :: 3 - Alpha',
            #'Development Status :: 4 - Beta',
            #'Development Status :: 5 - Production/Stable',
            #'Development Status :: 6 - Mature',
            #'Development Status :: 7 - Inactive',
            'Environment :: Console',
            #'Environment :: MacOS X',
            #'Environment :: No Input/Output (Daemon)',
            #'Environment :: Web Environment',
            #'Environment :: Win32 (MS Windows)',
            #'Environment :: X11 Applications',
            'Intended Audience :: Developers',
            'Intended Audience :: Manufacturing',
            #'Intended Audience :: End Users/Desktop',
            'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
            'Natural Language :: English',
            #'Operating System :: Microsoft :: Windows :: Windows 7',
            #'Operating System :: MacOS :: MacOS X',
            'Operating System :: OS Independent',
            'Programming Language :: Python :: 3',
            'Topic :: Office/Business :: Scheduling',
            'Topic :: Software Development :: Libraries',
            'Typing :: Typed'
        ],
        zip_safe=True)
